POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title": "pikkanen kahvi 2",
    "author": "Matti Nasa",
    "url": "http://kill.bill.com",
    "likes": "1",
    "userId": "5d5ebf3b381542727ebbf77c"
}